# Generated by Django 3.2.8 on 2021-10-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflearn_lecture', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytext',
            name='lecture_title1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mytext',
            name='lecture_title2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mytext',
            name='lecture_title3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mytext',
            name='lecture_title4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mytext',
            name='lecture_vidio1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mytext',
            name='lecture_vidio2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mytext',
            name='lecture_vidio3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mytext',
            name='lecture_vidio4',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
