# Generated by Django 3.2.8 on 2021-10-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflearn_lecture', '0008_auto_20211030_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytext',
            name='lecture_vidio1',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='mytext',
            name='lecture_vidio2',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='mytext',
            name='lecture_vidio3',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='mytext',
            name='lecture_vidio4',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
